###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "OWO",
    "age": 2,
    "email": "rawr"
}

###

GET http://localhost:9000/api/users HTTP/1.1

###

GET http://localhost:9000/api/users/63697b28caabd60997d0916c HTTP/1.1

###

PUT http://localhost:9000/api/users/63697b28caabd60997d0916c HTTP/1.1
Content-Type: application/json

{
    "name": "Carlos Zulueta Rafael",
    "age": 25,
    "email": "carlos@gmail.com"
}

###

DELETE http://localhost:9000/api/users/63697e3684065ba557ff91f2 HTTP/1.1